# Generated by Django 4.1.2 on 2023-09-12 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Day",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_number",
                    models.IntegerField(blank=True, max_length=10, null=True),
                ),
                ("meal_1", models.TextField(blank=True, max_length=10, null=True)),
                ("meal_2", models.TextField(blank=True, max_length=10, null=True)),
                ("meal_3", models.TextField(blank=True, max_length=10, null=True)),
                ("meal_4", models.TextField(blank=True, max_length=10, null=True)),
                ("meal_5", models.TextField(blank=True, max_length=10, null=True)),
                ("meal_6", models.TextField(blank=True, max_length=10, null=True)),
                ("meal_7", models.TextField(blank=True, max_length=10, null=True)),
                ("created", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Days",
            },
        ),
    ]
