# Generated by Django 4.1.2 on 2023-09-12 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Component",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number_in_grams", models.IntegerField(blank=True, null=True)),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("number_of_calories", models.IntegerField(blank=True, null=True)),
                ("created", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Components",
            },
        ),
        migrations.CreateModel(
            name="Meal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "meal_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PreBreakfast", "PreBreakfast"),
                            ("Breakfast", "Breakfast"),
                            ("PreWorkout ", "PreWorkout"),
                            ("After Workout", "After Workout"),
                            ("Dinner", "Dinner"),
                            ("After Dinner", "After Dinner"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("created", models.DateTimeField(auto_now=True)),
                ("components", models.ManyToManyField(to="customization.component")),
            ],
            options={
                "verbose_name_plural": "Meals",
            },
        ),
        migrations.CreateModel(
            name="Day",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day_number", models.IntegerField(blank=True, null=True)),
                ("created", models.DateTimeField(auto_now=True)),
                (
                    "meal_1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meal_1",
                        to="customization.meal",
                    ),
                ),
                (
                    "meal_2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meal_2",
                        to="customization.meal",
                    ),
                ),
                (
                    "meal_3",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meal_3",
                        to="customization.meal",
                    ),
                ),
                (
                    "meal_4",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meal_4",
                        to="customization.meal",
                    ),
                ),
                (
                    "meal_5",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meal_5",
                        to="customization.meal",
                    ),
                ),
                (
                    "meal_6",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meal_6",
                        to="customization.meal",
                    ),
                ),
                (
                    "meal_7",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meal_7",
                        to="customization.meal",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Days",
            },
        ),
    ]
