# Generated by Django 4.1.2 on 2023-09-12 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customization", "0002_alter_day_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="day",
            name="meal_1",
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="day",
            name="meal_2",
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="day",
            name="meal_3",
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="day",
            name="meal_4",
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="day",
            name="meal_5",
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="day",
            name="meal_6",
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="day",
            name="meal_7",
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
