# Generated by Django 4.1.2 on 2023-09-12 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "customization",
            "0003_alter_day_meal_1_alter_day_meal_2_alter_day_meal_3_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Component",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number_in_grams",
                    models.IntegerField(blank=True, max_length=10, null=True),
                ),
                ("name", models.TextField(blank=True, max_length=100, null=True)),
                (
                    "number_of_calories",
                    models.TextField(blank=True, max_length=100, null=True),
                ),
                ("created", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Components",
            },
        ),
    ]
