# Generated by Django 4.1.2 on 2023-09-12 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customization", "0005_meal"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="meal",
            name="component_1",
        ),
        migrations.RemoveField(
            model_name="meal",
            name="component_2",
        ),
        migrations.RemoveField(
            model_name="meal",
            name="component_3",
        ),
        migrations.RemoveField(
            model_name="meal",
            name="component_4",
        ),
        migrations.RemoveField(
            model_name="meal",
            name="component_5",
        ),
        migrations.AddField(
            model_name="meal",
            name="components",
            field=models.ManyToManyField(to="customization.component"),
        ),
    ]
