# Generated by Django 4.1.2 on 2023-09-12 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "customization",
            "0006_remove_meal_component_1_remove_meal_component_2_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="component",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="component",
            name="number_of_calories",
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
    ]
