# Generated by Django 4.1.2 on 2023-09-12 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customization", "0007_alter_component_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="meal",
            name="meal_number",
        ),
        migrations.AddField(
            model_name="meal",
            name="meal_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PreBreakfast", "PreBreakfast"),
                    ("Breakfast", "Breakfast"),
                    ("PreWorkout ", "PreWorkout"),
                    ("After Workout", "After Workout"),
                    ("Dinner", "Dinner"),
                    ("After Dinner", "After Dinner"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
