# Generated by Django 4.1.2 on 2023-09-12 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customization", "0008_remove_meal_meal_number_meal_meal_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="meal",
            name="title",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
