# Generated by Django 4.1.2 on 2023-09-12 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("customization", "0009_meal_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="day",
            name="meal_1",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="meal_1",
                to="customization.meal",
            ),
        ),
        migrations.AlterField(
            model_name="day",
            name="meal_2",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="meal_2",
                to="customization.meal",
            ),
        ),
        migrations.AlterField(
            model_name="day",
            name="meal_3",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="meal_3",
                to="customization.meal",
            ),
        ),
        migrations.AlterField(
            model_name="day",
            name="meal_4",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="meal_4",
                to="customization.meal",
            ),
        ),
        migrations.AlterField(
            model_name="day",
            name="meal_5",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="meal_5",
                to="customization.meal",
            ),
        ),
        migrations.AlterField(
            model_name="day",
            name="meal_6",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="meal_6",
                to="customization.meal",
            ),
        ),
        migrations.AlterField(
            model_name="day",
            name="meal_7",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="meal_7",
                to="customization.meal",
            ),
        ),
        migrations.AlterField(
            model_name="day",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
