# Generated by Django 4.1.2 on 2023-09-12 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "customization",
            "0010_alter_day_meal_1_alter_day_meal_2_alter_day_meal_3_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="component",
            name="full_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
