# Generated by Django 4.1.2 on 2023-09-12 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customization", "0011_component_full_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="component",
            name="full_name",
        ),
    ]
