# Generated by Django 4.1.2 on 2023-09-12 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customization", "0012_remove_component_full_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="component",
            name="number_in_grams",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="component",
            name="number_of_calories",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="day",
            name="day_number",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
