# Generated by Django 4.1.2 on 2023-09-12 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("customization", "0013_alter_component_number_in_grams_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="day",
            name="meal_5",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="meal_5",
                to="customization.meal",
            ),
        ),
        migrations.AlterField(
            model_name="day",
            name="meal_6",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="meal_6",
                to="customization.meal",
            ),
        ),
        migrations.AlterField(
            model_name="day",
            name="meal_7",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="meal_7",
                to="customization.meal",
            ),
        ),
    ]
