# Generated by Django 4.1.2 on 2023-09-12 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Register_Login", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="age",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
