# Generated by Django 4.1.2 on 2023-09-12 21:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "arabic_title",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("category", models.DateTimeField(auto_now=True)),
                (
                    "description",
                    models.TextField(blank=True, max_length=500, null=True),
                ),
            ],
            options={
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.CreateModel(
            name="workout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "arabic_title",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("created", models.DateTimeField(auto_now=True)),
                (
                    "category_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="type",
                        to="workout.category",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Workouts",
            },
        ),
        migrations.CreateModel(
            name="workout_week",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now=True)),
                ("finished", models.BooleanField(default=False)),
                ("week_number", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Weeks",
            },
        ),
        migrations.CreateModel(
            name="workout_day",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day_number", models.PositiveIntegerField(blank=True, null=True)),
                ("created", models.DateTimeField(auto_now=True)),
                ("finished", models.BooleanField(default=False)),
                ("week_number", models.PositiveIntegerField(blank=True, null=True)),
                ("number_of_sets", models.PositiveIntegerField(blank=True, null=True)),
                ("number_of_reps", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "workout",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work",
                        to="workout.workout",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Workout Days",
            },
        ),
    ]
