# Generated by Django 4.1.2 on 2023-10-02 21:44

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "arabic_title",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("created", models.DateTimeField(auto_now=True)),
                (
                    "description",
                    models.TextField(blank=True, max_length=500, null=True),
                ),
            ],
            options={
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.CreateModel(
            name="ClientPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("repeat_week_one", models.BooleanField(default=False)),
                ("created", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cl",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Client's Plan",
                "verbose_name_plural": "Client's Plans",
            },
        ),
        migrations.CreateModel(
            name="day",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now=True)),
                ("day_number", models.PositiveIntegerField()),
                ("done", models.BooleanField(default=False)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cat",
                        to="workout.category",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="userss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Day",
                "verbose_name_plural": "Client Exercise's Days",
            },
        ),
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "arabic_title",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "gif_file",
                    models.FileField(
                        upload_to="uploads/workouts",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["gif"]
                            )
                        ],
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, max_length=500, null=True),
                ),
                ("created", models.DateTimeField(auto_now=True)),
                (
                    "category_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="type",
                        to="workout.category",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Workouts",
            },
        ),
        migrations.CreateModel(
            name="user_exercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now=True)),
                (
                    "day",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="days",
                        to="workout.day",
                    ),
                ),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workouts",
                        to="workout.exercise",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="userssss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Exercise",
                "verbose_name_plural": "User Exercises",
            },
        ),
        migrations.CreateModel(
            name="workout_reps",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sets", models.PositiveIntegerField()),
                ("reps", models.PositiveBigIntegerField()),
                ("rest_time", models.PositiveBigIntegerField()),
                (
                    "user_workout",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workouts",
                        to="workout.user_exercise",
                    ),
                ),
            ],
            options={
                "verbose_name": "Exercise rep",
                "verbose_name_plural": "Exercise's reps",
            },
        ),
        migrations.CreateModel(
            name="Week",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "week_number",
                    models.CharField(
                        choices=[
                            ("Week 1", "Week 1"),
                            ("Week 2", "Week 2"),
                            ("Week 3", "Week 3"),
                            ("Week 4", "Week 4"),
                        ],
                        max_length=50,
                    ),
                ),
                ("done", models.BooleanField(default=False)),
                (
                    "client_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plans",
                        to="workout.clientplan",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Weeks",
            },
        ),
        migrations.AddField(
            model_name="day",
            name="week",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="weeks",
                to="workout.week",
            ),
        ),
    ]
