# Generated by Django 4.1.2 on 2023-10-02 21:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("workout", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="day",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="userss",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
