# Generated by Django 4.1.2 on 2023-09-12 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("workout", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="workout_day",
            name="category_type",
            field=models.ForeignKey(
                default=12,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cat",
                to="workout.category",
            ),
            preserve_default=False,
        ),
    ]
