# Generated by Django 4.1.2 on 2023-09-12 21:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workout", "0002_workout_day_category_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="workout",
            name="gif_file",
            field=models.FileField(
                default=12,
                upload_to="upload_workout",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["gif"]
                    )
                ],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="workout_week",
            name="expired",
            field=models.BooleanField(default=False),
        ),
    ]
