# Generated by Django 4.1.2 on 2023-09-12 21:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workout", "0003_workout_gif_file_workout_week_expired"),
    ]

    operations = [
        migrations.AddField(
            model_name="workout",
            name="description",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="workout",
            name="gif_file",
            field=models.FileField(
                upload_to="uploads/workouts",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["gif"]
                    )
                ],
            ),
        ),
    ]
