# Generated by Django 4.1.2 on 2023-09-12 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("workout", "0004_workout_description_alter_workout_gif_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workout_day",
            name="week_number",
        ),
        migrations.AddField(
            model_name="workout_day",
            name="week",
            field=models.ForeignKey(
                default=12,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="week",
                to="workout.workout_week",
            ),
            preserve_default=False,
        ),
    ]
