# Generated by Django 4.1.2 on 2023-09-12 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workout", "0005_remove_workout_day_week_number_workout_day_week"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workout_day",
            name="day_number",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Day 1", "Day 1"),
                    ("Day 2", "Day 2"),
                    ("Day 3", "Day 3"),
                    ("Day 4", "Day 4"),
                    ("Day 5", "Day 5"),
                    ("Day 6", "Day 6"),
                    ("Day 7", "Day 7"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
