# Generated by Django 4.1.2 on 2023-09-12 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workout", "0006_alter_workout_day_day_number"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="category",
            new_name="created",
        ),
    ]
