# Generated by Django 4.1.2 on 2023-09-12 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("workout", "0007_rename_category_category_created"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workout_day",
            name="number_of_reps",
        ),
        migrations.RemoveField(
            model_name="workout_day",
            name="number_of_sets",
        ),
        migrations.CreateModel(
            name="number_of_sets",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number_of_sets", models.PositiveIntegerField()),
                ("number_of_reps", models.PositiveIntegerField()),
                (
                    "workout_day",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sets",
                        to="workout.workout_day",
                    ),
                ),
            ],
        ),
    ]
