# Generated by Django 4.1.2 on 2023-09-12 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("workout", "0008_remove_workout_day_number_of_reps_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workout_day",
            name="day_number",
        ),
        migrations.AlterField(
            model_name="workout_week",
            name="week_number",
            field=models.CharField(
                blank=True,
                choices=[
                    ("week 1", "week 1"),
                    ("week 2", "week 2"),
                    ("week 3", "week 3"),
                    ("week 4", "week 4"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="day",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_number",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1", "1"),
                            ("2", "2"),
                            ("3", "3"),
                            ("4", "4"),
                            ("5", "5"),
                            ("6", "6"),
                            ("7", "7"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("created", models.DateTimeField(auto_now=True)),
                (
                    "category_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="catType",
                        to="workout.category",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Workouts",
            },
        ),
        migrations.AddField(
            model_name="workout_day",
            name="day",
            field=models.ForeignKey(
                default=12,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="day",
                to="workout.day",
            ),
            preserve_default=False,
        ),
    ]
