# Generated by Django 4.1.2 on 2023-09-12 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workout", "0009_remove_workout_day_day_number_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workout_day",
            name="day",
        ),
    ]
