# Generated by Django 4.1.2 on 2023-09-12 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("workout", "0010_remove_workout_day_day"),
    ]

    operations = [
        migrations.AddField(
            model_name="workout_day",
            name="day",
            field=models.ForeignKey(
                default=12,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="day",
                to="workout.day",
            ),
            preserve_default=False,
        ),
    ]
