# Generated by Django 4.1.2 on 2023-09-12 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workout", "0011_workout_day_day"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="day",
            new_name="workoutDayTitle",
        ),
    ]
