# Generated by Django 4.1.2 on 2023-09-12 23:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("workout", "0012_rename_day_workoutdaytitle"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="workoutdaytitle",
            options={"verbose_name_plural": "workoutDayTitle"},
        ),
        migrations.AddField(
            model_name="workoutdaytitle",
            name="user",
            field=models.ForeignKey(
                default=12,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="userClient",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
