# Generated by Django 4.1.2 on 2023-09-12 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workout", "0013_alter_workoutdaytitle_options_workoutdaytitle_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workout_day",
            name="category_type",
        ),
    ]
