# Generated by Django 4.1.2 on 2023-09-13 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workout", "0014_remove_workout_day_category_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="workoutdaytitle",
            name="week_number",
            field=models.CharField(
                blank=True,
                choices=[
                    ("week 1", "week 1"),
                    ("week 2", "week 2"),
                    ("week 3", "week 3"),
                    ("week 4", "week 4"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
