# Generated by Django 4.1.2 on 2023-09-13 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workout", "0015_workoutdaytitle_week_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workout_day",
            name="week",
        ),
    ]
