# Generated by Django 4.1.2 on 2023-09-13 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("workout", "0016_remove_workout_day_week"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workout_day",
            name="day",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="daily",
                to="workout.workoutdaytitle",
            ),
        ),
    ]
