# Generated by Django 4.1.2 on 2023-09-13 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workout", "0018_rename_workoutdaytitle_workoutplanning_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="workoutplanning",
            options={"verbose_name_plural": "workoutPlanning"},
        ),
        migrations.AlterField(
            model_name="workoutplanning",
            name="week_number",
            field=models.CharField(
                blank=True,
                choices=[
                    ("week_1", "week_1"),
                    ("week_2", "week_2"),
                    ("week_3", "week_3"),
                    ("week_4", "week_4"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
