# Generated by Django 4.1.2 on 2023-09-23 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workout", "0019_alter_workoutplanning_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="workoutplanning",
            options={"verbose_name_plural": "Workout Plans"},
        ),
        migrations.AddField(
            model_name="number_of_sets",
            name="day_1",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="number_of_sets",
            name="day_2",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="number_of_sets",
            name="day_3",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="number_of_sets",
            name="day_4",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="number_of_sets",
            name="day_5",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="number_of_sets",
            name="day_6",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="number_of_sets",
            name="day_7",
            field=models.BooleanField(default=False),
        ),
    ]
