# Generated by Django 4.1.2 on 2023-09-23 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workout", "0020_alter_workoutplanning_options_number_of_sets_day_1_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="number_of_sets",
            name="day_1",
        ),
        migrations.RemoveField(
            model_name="number_of_sets",
            name="day_2",
        ),
        migrations.RemoveField(
            model_name="number_of_sets",
            name="day_3",
        ),
        migrations.RemoveField(
            model_name="number_of_sets",
            name="day_4",
        ),
        migrations.RemoveField(
            model_name="number_of_sets",
            name="day_5",
        ),
        migrations.RemoveField(
            model_name="number_of_sets",
            name="day_6",
        ),
        migrations.RemoveField(
            model_name="number_of_sets",
            name="day_7",
        ),
    ]
