# Generated by Django 4.1.2 on 2023-09-23 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("workout", "0021_remove_number_of_sets_day_1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="number_of_sets",
            name="work_plans",
            field=models.ForeignKey(
                default=12,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="workplan",
                to="workout.workoutplanning",
            ),
            preserve_default=False,
        ),
    ]
