# Generated by Django 4.1.2 on 2023-09-23 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("workout", "0022_number_of_sets_work_plans"),
    ]

    operations = [
        migrations.CreateModel(
            name="Week",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number_of_sets", models.PositiveIntegerField()),
                ("number_of_reps", models.PositiveIntegerField()),
                (
                    "category_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cito",
                        to="workout.category",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="workout_day",
            name="day",
        ),
        migrations.AddField(
            model_name="workout_day",
            name="user",
            field=models.ForeignKey(
                default=12,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="userClient",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="workoutplanning",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cl",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(
            name="number_of_sets",
        ),
        migrations.AddField(
            model_name="week",
            name="day",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="daily",
                to="workout.workoutplanning",
            ),
        ),
        migrations.AddField(
            model_name="week",
            name="workout_day",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sets",
                to="workout.workout_day",
            ),
        ),
    ]
