# Generated by Django 4.1.2 on 2023-09-24 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workout", "0027_remove_exercise_workout_day_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workout_day",
            name="user",
        ),
        migrations.RemoveField(
            model_name="workout_day",
            name="workout",
        ),
        migrations.DeleteModel(
            name="Week",
        ),
        migrations.DeleteModel(
            name="workout_day",
        ),
    ]
