# Generated by Django 4.1.2 on 2023-09-24 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("workout", "0029_workout_day_week"),
    ]

    operations = [
        migrations.CreateModel(
            name="day",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="userClient",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Workout Days",
            },
        ),
        migrations.RemoveField(
            model_name="week",
            name="category_type",
        ),
        migrations.RemoveField(
            model_name="week",
            name="number_of_reps",
        ),
        migrations.RemoveField(
            model_name="week",
            name="number_of_sets",
        ),
        migrations.RemoveField(
            model_name="week",
            name="workout_day",
        ),
        migrations.DeleteModel(
            name="workout_day",
        ),
        migrations.AlterField(
            model_name="week",
            name="day",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="day",
                to="workout.day",
            ),
        ),
    ]
