# Generated by Django 4.1.2 on 2023-09-24 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("workout", "0030_day_remove_week_category_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workoutplanning",
            name="category_type",
        ),
        migrations.RemoveField(
            model_name="workoutplanning",
            name="day_number",
        ),
        migrations.RemoveField(
            model_name="workoutplanning",
            name="week_number",
        ),
        migrations.AddField(
            model_name="week",
            name="workoutplan",
            field=models.ForeignKey(
                default=12,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="plans",
                to="workout.workoutplanning",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="workoutplanning",
            name="day",
            field=models.ForeignKey(
                default=14,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="days",
                to="workout.day",
            ),
            preserve_default=False,
        ),
    ]
