# Generated by Django 4.1.2 on 2023-09-24 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("workout", "0032_remove_workoutplanning_day"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="week",
            name="day",
        ),
        migrations.AddField(
            model_name="day",
            name="week",
            field=models.ForeignKey(
                default=12,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="weeks",
                to="workout.week",
            ),
            preserve_default=False,
        ),
    ]
