# Generated by Django 4.1.2 on 2023-09-24 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("workout", "0034_author_book_chapter"),
    ]

    operations = [
        migrations.AddField(
            model_name="day",
            name="workoutplan",
            field=models.ForeignKey(
                default=76,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="plan",
                to="workout.workoutplanning",
            ),
            preserve_default=False,
        ),
    ]
