# Generated by Django 4.1.2 on 2023-09-24 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workout", "0035_day_workoutplan"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="author",
        ),
        migrations.RemoveField(
            model_name="chapter",
            name="book",
        ),
        migrations.RemoveField(
            model_name="day",
            name="workoutplan",
        ),
        migrations.DeleteModel(
            name="Author",
        ),
        migrations.DeleteModel(
            name="Book",
        ),
        migrations.DeleteModel(
            name="Chapter",
        ),
    ]
