# Generated by Django 4.1.2 on 2023-09-24 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workout", "0037_workoutday_workoutyyy_workoutplan_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workoutplan",
            name="user",
        ),
        migrations.RemoveField(
            model_name="workoutyyy",
            name="workout_day",
        ),
        migrations.DeleteModel(
            name="WorkoutDay",
        ),
        migrations.DeleteModel(
            name="WorkoutPlan",
        ),
        migrations.DeleteModel(
            name="Workoutyyy",
        ),
    ]
