# Generated by Django 4.1.2 on 2023-09-24 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("workout", "0038_remove_workoutplan_user_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Week_four",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "workoutplan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weekfour",
                        to="workout.workoutplanning",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Week_one",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "workoutplan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weekone",
                        to="workout.workoutplanning",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Week_three",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "workoutplan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weekthree",
                        to="workout.workoutplanning",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Week_two",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "workoutplan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weektwo",
                        to="workout.workoutplanning",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="day",
            name="week",
        ),
        migrations.DeleteModel(
            name="Week",
        ),
    ]
