# Generated by Django 4.1.2 on 2023-09-24 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("workout", "0039_week_four_week_one_week_three_week_two_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Week",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "workoutplan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plans",
                        to="workout.workoutplanning",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Weeks",
            },
        ),
        migrations.RemoveField(
            model_name="week_one",
            name="workoutplan",
        ),
        migrations.RemoveField(
            model_name="week_three",
            name="workoutplan",
        ),
        migrations.RemoveField(
            model_name="week_two",
            name="workoutplan",
        ),
        migrations.DeleteModel(
            name="Week_four",
        ),
        migrations.DeleteModel(
            name="Week_one",
        ),
        migrations.DeleteModel(
            name="Week_three",
        ),
        migrations.DeleteModel(
            name="Week_two",
        ),
        migrations.AddField(
            model_name="day",
            name="week",
            field=models.ForeignKey(
                default=12,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="weeks",
                to="workout.week",
            ),
            preserve_default=False,
        ),
    ]
