# Generated by Django 4.1.2 on 2023-09-24 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("workout", "0040_week_remove_week_one_workoutplan_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LevelOne",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="TopLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name="day",
            name="user",
        ),
        migrations.AddField(
            model_name="day",
            name="workout",
            field=models.ForeignKey(
                default=142,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="workouts",
                to="workout.workout",
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="LevelTwo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="workout.levelone",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LevelThree",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="workout.leveltwo",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="levelone",
            name="level",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="workout.toplevel"
            ),
        ),
    ]
