# Generated by Django 4.1.2 on 2023-09-24 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("workout", "0041_levelone_toplevel_remove_day_user_day_workout_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="user_workout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sets", models.PositiveIntegerField()),
                ("reps", models.PositiveBigIntegerField()),
                ("created", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Workout Days",
            },
        ),
        migrations.RemoveField(
            model_name="day",
            name="workout",
        ),
        migrations.DeleteModel(
            name="LevelThree",
        ),
        migrations.AddField(
            model_name="user_workout",
            name="day",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="days",
                to="workout.day",
            ),
        ),
        migrations.AddField(
            model_name="user_workout",
            name="workout",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="workouts",
                to="workout.workout",
            ),
        ),
    ]
