# Generated by Django 4.1.2 on 2023-09-24 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("workout", "0042_user_workout_remove_day_workout_delete_levelthree_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user_workout",
            name="reps",
        ),
        migrations.RemoveField(
            model_name="user_workout",
            name="sets",
        ),
        migrations.CreateModel(
            name="workout_reps",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sets", models.PositiveIntegerField()),
                ("reps", models.PositiveBigIntegerField()),
                (
                    "user_workout",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workouts",
                        to="workout.user_workout",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Workout Days",
            },
        ),
    ]
