# Generated by Django 4.1.2 on 2023-09-24 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("workout", "0043_remove_user_workout_reps_remove_user_workout_sets_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="day",
            name="category",
            field=models.ForeignKey(
                default=14,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cat",
                to="workout.category",
            ),
            preserve_default=False,
        ),
    ]
