# Generated by Django 4.1.2 on 2023-09-24 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workout", "0044_day_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="day",
            name="done",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="day",
            name="off",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="week",
            name="done",
            field=models.BooleanField(default=False),
        ),
    ]
