# Generated by Django 4.1.2 on 2023-09-24 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workout", "0045_day_done_day_off_week_done"),
    ]

    operations = [
        migrations.AddField(
            model_name="week",
            name="repeat_week_one",
            field=models.BooleanField(default=False),
        ),
    ]
