# Generated by Django 4.1.2 on 2023-09-24 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workout", "0046_week_repeat_week_one"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="week",
            name="repeat_week_one",
        ),
        migrations.AddField(
            model_name="workoutplanning",
            name="repeat_week_one",
            field=models.BooleanField(default=False),
        ),
    ]
