# Generated by Django 4.1.2 on 2023-09-26 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workout", "0047_remove_week_repeat_week_one_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="leveltwo",
            name="level",
        ),
        migrations.DeleteModel(
            name="LevelOne",
        ),
        migrations.DeleteModel(
            name="LevelTwo",
        ),
        migrations.DeleteModel(
            name="TopLevel",
        ),
    ]
