# Generated by Django 4.1.2 on 2023-09-26 21:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("workout", "0048_remove_leveltwo_level_delete_levelone_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user_workout",
            options={"verbose_name_plural": "User Workouts"},
        ),
        migrations.AddField(
            model_name="day",
            name="user",
            field=models.ForeignKey(
                default=15,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="userss",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
