# Generated by Django 4.1.2 on 2023-09-26 22:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("workout", "0049_alter_user_workout_options_day_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="user_workout",
            name="user",
            field=models.ForeignKey(
                default=155,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="userssss",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
