# Generated by Django 4.1.2 on 2023-09-26 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workout", "0050_user_workout_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="day",
            name="day_number",
            field=models.PositiveIntegerField(default=100),
            preserve_default=False,
        ),
    ]
