# Generated by Django 4.1.2 on 2023-09-26 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workout", "0051_day_day_number"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="workout_reps",
            options={"verbose_name_plural": "Workout reps"},
        ),
        migrations.AddField(
            model_name="workout_reps",
            name="rest_time",
            field=models.PositiveBigIntegerField(default=1092),
            preserve_default=False,
        ),
    ]
