# Generated by Django 4.1.2 on 2023-09-26 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workout", "0052_alter_workout_reps_options_workout_reps_rest_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="day",
            name="off",
        ),
    ]
