# Generated by Django 4.1.2 on 2023-09-26 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workout", "0053_remove_day_off"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="day",
            options={
                "verbose_name": "User Exercise's Days",
                "verbose_name_plural": "User Exercise's Days",
            },
        ),
        migrations.AlterModelOptions(
            name="user_workout",
            options={
                "verbose_name": "Exercise",
                "verbose_name_plural": "User Exercises",
            },
        ),
        migrations.AlterModelOptions(
            name="workout_reps",
            options={
                "verbose_name": "Exercise rep",
                "verbose_name_plural": "Exercise's reps",
            },
        ),
        migrations.AlterModelOptions(
            name="workoutplanning",
            options={
                "verbose_name": "Client's Plan",
                "verbose_name_plural": "Client's Plans",
            },
        ),
        migrations.AddField(
            model_name="week",
            name="week_number",
            field=models.PositiveIntegerField(default=123),
            preserve_default=False,
        ),
    ]
