# Generated by Django 4.1.2 on 2023-09-26 22:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("workout", "0055_rename_workout_exercise_user_exercise_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="day",
            options={
                "verbose_name": "Client Exercise's Days",
                "verbose_name_plural": "Client Exercise's Days",
            },
        ),
        migrations.AlterField(
            model_name="workoutplanning",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cl",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
