# Generated by Django 4.1.2 on 2023-09-26 22:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("workout", "0056_alter_day_options_alter_workoutplanning_user"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="workoutPlanning",
            new_name="ClientPlan",
        ),
    ]
