# Generated by Django 4.1.2 on 2023-09-26 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workout", "0057_rename_workoutplanning_clientplan"),
    ]

    operations = [
        migrations.RenameField(
            model_name="week",
            old_name="workoutplan",
            new_name="client_plan",
        ),
    ]
