# Generated by Django 4.1.2 on 2023-09-26 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workout", "0059_alter_week_week_number"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="day",
            options={
                "verbose_name": "Day",
                "verbose_name_plural": "Client Exercise's Days",
            },
        ),
        migrations.AlterField(
            model_name="week",
            name="week_number",
            field=models.CharField(
                choices=[
                    ("Week 1", "Week 1"),
                    ("Week 2", "Week 2"),
                    ("Week 3", "Week 3"),
                    ("Week 4", "Week 4"),
                ],
                max_length=50,
            ),
        ),
    ]
