# Generated by Django 4.1.2 on 2023-10-02 21:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="pending_upgrades",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(blank=True, null=True, upload_to="")),
                (
                    "comment_from_client",
                    models.TextField(blank=True, max_length=300, null=True),
                ),
                ("upgraded", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clients",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Pending Upgrades",
            },
        ),
        migrations.CreateModel(
            name="Nutrition_day",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day_number", models.PositiveIntegerField(blank=True, null=True)),
                ("total_calories", models.PositiveIntegerField(blank=True, null=True)),
                ("created", models.DateTimeField(auto_now=True)),
                ("Done", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Nutrition Days",
            },
        ),
        migrations.CreateModel(
            name="Meal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("components", models.TextField(blank=True, max_length=300, null=True)),
                (
                    "meal_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PreBreakfast", "PreBreakfast"),
                            ("Breakfast", "Breakfast"),
                            ("PreWorkout ", "PreWorkout"),
                            ("After Workout", "After Workout"),
                            ("Dinner", "Dinner"),
                            ("After Dinner", "After Dinner"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("created", models.DateTimeField(auto_now=True)),
                ("finished", models.BooleanField(default=False)),
                (
                    "total_meal_calorie",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "day",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="day",
                        to="Nutrition.nutrition_day",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Meals",
            },
        ),
    ]
