# Generated by Django 4.1.2 on 2023-09-26 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Nutrition", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="day",
            name="meal_1",
        ),
        migrations.RemoveField(
            model_name="day",
            name="meal_2",
        ),
        migrations.RemoveField(
            model_name="day",
            name="meal_3",
        ),
        migrations.RemoveField(
            model_name="day",
            name="meal_4",
        ),
        migrations.RemoveField(
            model_name="day",
            name="meal_5",
        ),
        migrations.RemoveField(
            model_name="day",
            name="meal_6",
        ),
        migrations.RemoveField(
            model_name="day",
            name="meal_7",
        ),
        migrations.AddField(
            model_name="day",
            name="total_calories",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="meal",
            name="day",
            field=models.ForeignKey(
                default=154,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="day",
                to="Nutrition.day",
            ),
            preserve_default=False,
        ),
    ]
