# Generated by Django 4.1.2 on 2023-09-26 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Nutrition", "0002_remove_day_meal_1_remove_day_meal_2_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="meal",
            name="title",
        ),
        migrations.RemoveField(
            model_name="meal",
            name="components",
        ),
        migrations.AddField(
            model_name="meal",
            name="components",
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
