# Generated by Django 4.1.2 on 2023-09-26 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Nutrition", "0003_remove_meal_title_remove_meal_components_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Component",
        ),
    ]
