# Generated by Django 4.1.2 on 2023-09-26 20:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Nutrition", "0004_delete_component"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Day",
            new_name="Nutrition_day",
        ),
        migrations.AlterModelOptions(
            name="nutrition_day",
            options={"verbose_name_plural": "Nutrition Days"},
        ),
    ]
