# Generated by Django 4.1.2 on 2023-09-26 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Nutrition", "0005_rename_day_nutrition_day_alter_nutrition_day_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="meal",
            name="total_meal_calorie",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="nutrition_day",
            name="day_number",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="nutrition_day",
            name="total_calories",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
