# Generated by Django 4.1.2 on 2023-09-26 21:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Nutrition", "0006_meal_total_meal_calorie_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="pending_upgrades",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(blank=True, null=True, upload_to="")),
                (
                    "comment_from_client",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PreBreakfast", "PreBreakfast"),
                            ("Breakfast", "Breakfast"),
                            ("PreWorkout ", "PreWorkout"),
                            ("After Workout", "After Workout"),
                            ("Dinner", "Dinner"),
                            ("After Dinner", "After Dinner"),
                        ],
                        max_length=250,
                        null=True,
                    ),
                ),
                ("upgraded", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clients",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Pending Upgrades",
            },
        ),
    ]
