# Generated by Django 4.1.2 on 2023-09-26 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Nutrition", "0007_pending_upgrades"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pending_upgrades",
            name="comment_from_client",
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
