# Generated by Django 4.1.2 on 2023-09-26 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Nutrition", "0008_alter_pending_upgrades_comment_from_client"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pending_upgrades",
            name="upgraded",
            field=models.BooleanField(default=True),
        ),
    ]
